### ISSUE TITLE
Compatibility with com.typesafe.play.sbt-plugin:2.7.0

### ISSUE THREAD

**Issue by vsukharev** [zalando-incubator/play-zhewbacca#61]
We have a project using `play-zhewbacca:0.3.4` and `com.typesafe.play.sbt-plugin:2.6.21`.
After bumping `sbt-plugin` to 2.7.0, `play-zhewbacca:0.3.4` appeared to be binary incompatible with the following runtime error
```
java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;	
at org.zalando.zhewbacca.TokenInfo$.<init>(TokenInfo.scala:11)
```
It would be nice to have next `play-zhewbacca` version compatible with `sbt-plugin:2.7.0` please.
